# Generated by Django 5.0.4 on 2026-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(db_index=True, max_length=255)),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('task_question', models.TextField(blank=True, null=True)),
                ('essay_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('scores', models.JSONField(blank=True, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=60)),
                ('cache_hit', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supabase_uid', 'created_at'], name='evaluator_e_supabas_bede91_idx'), models.Index(fields=['supabase_uid', 'status'], name='evaluator_e_supabas_35e60b_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(max_length=60)),
                ('api_key_index', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('cache_hits', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'model'],
                'unique_together': {('date', 'model', 'api_key_index')},
            },
        ),
    ]
